name: Pipeline for NSDL E-Sign - Dev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./nsdl_pan_wrapper"
          REMOTE_HOST: "ec2-65-0-125-86.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user"
        - run: |
           echo "Building the jar file"
           cd /home/ec2-user
           mvn package
       
  Build:
    name: Building the code
    runs-on: self-hosted   

    steps:
      - uses: actions/checkout@v2
      - run: |
           echo "Building the jar file"
           cd /home/ec2-user/nsdl_pan_wrapper
           mvn package

        