name: Pipeline for NSDL E-Sign - Dev

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Deploy the code to ec2
    uses: actions/checkout@v1
    runs-on: self-hosted
    steps:
      
      - uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./nsdl_esign_wrapper"
          REMOTE_HOST: "ec2-65-0-125-86.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user"
        - run: |
           echo "Building the jar file"
           cd /home/ec2-user
           mvn package