name: Pipeline for NSDL E-Sign - Dev

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Deploy the code to ec2
    runs-on: self-hosted
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy the code to ec2-machine
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./nsdl_esign_wrapper"
          REMOTE_HOST: "ec2-3-111-0-99.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/java-wrappers/nsdl-esign"

      - name: Building the code
        uses: actions/checkout@v1
        - run: |
           echo "Building the jar file"
           cd /home/ec2-user/java-wrappers/nsdl-pan/nsdl_pan_wrapper
           mvn package